<h1>Add a Meetup</h1>

<?php
    $form = $this->form; /* @var $form \Zend\Form\Form */
?>

<?= $this->form()->openTag($form); ?>

<?= $this->formRow($form->get('title')) ?>
<?= $this->formRow($form->get('description')) ?>
<?= $this->formRow($form->get('startedAt')) ?>
<?= $this->formRow($form->get('endedAt')) ?>
<?= $this->formInput($form->get('submit')) ?>

<?= $this->form()->closeTag($form); ?>
